/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 30.09.2026 18:24:26

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1472;
#else
constexpr int kTensorArenaSize = 448;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,13 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) float tensor_data1[3*10] = { 
  0.37520170211791992, 0.076462864875793457, 0.57208549976348877, -0.58694660663604736, -0.25884437561035156, 0.40151837468147278, 0.46214032173156738, -0.59954917430877686, -0.66304725408554077, 0.48650571703910828, 
  0.37188905477523804, 0.38633811473846436, -0.12294971942901611, -0.35739719867706299, -0.60818427801132202, -0.035927187651395798, 0.1954021155834198, -0.45944646000862122, 0.037042979151010513, -0.15830868482589722, 
  -0.52812892198562622, -0.12115943431854248, 0.66433978080749512, -0.067760556936264038, -0.58601731061935425, -0.59654659032821655, -0.5298391580581665, -0.36959472298622131, 0.64523226022720337, 0.19531653821468353, 
};
const TfArray<2, int> tensor_dimension1 = { 2, { 3,10 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) float tensor_data2[10*20] = { 
  0.23812104761600494, -0.29567396640777588, -0.28040498495101929, 0.049101203680038452, 0.36025974154472351, 0.11527132987976074, 0.41168442368507385, -0.42092263698577881, -0.043621979653835297, -0.13522264361381531, 0.067515745759010315, 0.071906685829162598, 0.31416007876396179, 0.41761940717697144, 0.18682214617729187, -0.37045586109161377, 0.0690450519323349, -0.10031795501708984, -0.21073265373706818, 0.088357120752334595, 
  -0.21513541042804718, -0.43652644753456116, 0.25989925861358643, 0.25670373439788818, 0.20556908845901489, -0.15646842122077942, -0.19914223253726959, -0.36983609199523926, -0.35554879903793335, 0.069873809814453125, -0.20073221623897552, -0.2023371160030365, 0.2409820556640625, 0.084498703479766846, 0.26755255460739136, 0.3430597186088562, -0.19190970063209534, 0.13136303424835205, -0.1693665087223053, -0.11774033308029175, 
  -0.086540102958679199, -0.36983108520507812, -0.011426568031311035, 0.40303337574005127, -0.18503651022911072, -0.22609998285770416, -0.13627669215202332, 0.078819572925567627, -0.15676471590995789, -0.043710947036743164, 0.12338340282440186, 0.19389015436172485, -0.081969767808914185, -0.33017858862876892, -0.050489902496337891, -0.26666605472564697, 0.32243669033050537, -0.3727266788482666, -0.38322222232818604, -0.30915829539299011, 
  0.30813243985176086, 0.051235824823379517, 0.35322993993759155, 0.013337910175323486, -0.25275728106498718, 0.3544025719165802, -0.21238668262958527, -0.18191644549369812, -0.1139676496386528, 0.34465950727462769, 0.37528076767921448, 0.18503981828689575, -0.20618467032909393, -0.36630383133888245, -0.018010174855589867, -0.17788471281528473, -0.03060489147901535, -0.20571751892566681, 0.4681398868560791, 0.32163810729980469, 
  -0.20512457191944122, 0.22864800691604614, -0.36935180425643921, -0.16372278332710266, -0.35634386539459229, 0.23844392597675323, -0.16949093341827393, 0.10276287794113159, -0.35277539491653442, 0.20511351525783539, 0.34554034471511841, 0.21861153841018677, -0.1077130138874054, 0.18902230262756348, 0.063349038362503052, -0.36372420191764832, -0.2168152779340744, 0.38466089963912964, 0.24865628778934479, 0.22064423561096191, 
  -0.33281230926513672, 0.26865863800048828, -0.25390893220901489, 0.19467127323150635, -0.10769827663898468, -0.44642287492752075, -0.025847317650914192, 0.31606143712997437, -0.4336237907409668, -0.17979496717453003, 0.30724102258682251, 0.22912448644638062, -0.19458532333374023, 0.26137164235115051, -0.081405080854892731, -0.32975491881370544, -0.14094427227973938, 0.23669981956481934, -0.25955837965011597, 0.091873422265052795, 
  0.29967790842056274, 0.18086844682693481, -0.24287232756614685, -0.30041342973709106, 0.28945049643516541, 0.2590528130531311, 0.022689994424581528, -0.14436368644237518, -0.11851414293050766, -0.034006170928478241, 0.22162173688411713, 0.15596038103103638, -0.32310658693313599, -0.17358583211898804, 0.016764117404818535, -0.10090538114309311, 0.1818186491727829, -0.068544209003448486, -0.10522907227277756, -0.14135138690471649, 
  0.006299144122749567, 0.34791058301925659, 0.17830127477645874, 0.23511844873428345, 0.014620746485888958, 0.36028203368186951, 0.38812431693077087, -0.42450523376464844, 0.43627440929412842, -0.080225579440593719, -0.2250295877456665, 0.4315333366394043, 0.3030204176902771, -0.10319361090660095, -0.33505746722221375, 0.19092845916748047, 0.37398803234100342, 0.020873993635177612, 0.085829541087150574, 0.32153928279876709, 
  0.23575006425380707, 0.15565967559814453, 0.21572920680046082, 0.15653890371322632, 0.34193199872970581, 0.1278454065322876, -0.40564852952957153, -0.096027389168739319, -0.10704084485769272, 0.047066181898117065, 0.37008675932884216, 0.081783950328826904, -0.018651306629180908, -0.39885354042053223, -0.12464999407529831, 0.42559975385665894, -0.33315008878707886, 0.27132850885391235, -0.18146216869354248, -0.12165585905313492, 
  0.1718033105134964, -0.27388951182365417, -0.048316787928342819, -0.0076735317707061768, 0.31837508082389832, 0.38615024089813232, -0.065773211419582367, 0.055693890899419785, 0.3093298077583313, -0.35648933053016663, -0.21762973070144653, 0.18616098165512085, -0.28586220741271973, -0.19181250035762787, 0.22692656517028809, -0.076753832399845123, -0.070471644401550293, 0.33945399522781372, 0.010248482227325439, 0.29847115278244019, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 10,20 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) float tensor_data3[10] = { -0.012555207125842571, 0, 0, 0.067516833543777466, -0.030011510476469994, 0.018639380112290382, -0.024252969771623611, 0.039084803313016891, 0.009013681672513485, 0.021541418507695198, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) float tensor_data4[20] = { 0.045799989253282547, 0, 0.014087026938796043, 0, -0.016794050112366676, -0.015838155522942543, -0.011703150346875191, 0.025735681876540184, 0.013955526985228062, -0.025948090478777885, -0.016803711652755737, 0, 0.060635581612586975, -0.015169740654528141, -0.009912506677210331, 0.015321503393352032, 0.031000794842839241, 0, -0.018833747133612633, -0.0010568753350526094, };
const TfArray<1, int> tensor_dimension4 = { 1, { 20 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) float tensor_data5[3] = { -0.040721733123064041, 0.050777088850736618, 0.011612202972173691, };
const TfArray<1, int> tensor_dimension5 = { 1, { 3 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) float tensor_data6[20*13] = { 
  -0.0056990720331668854, -0.05567362904548645, -0.09322819858789444, 0.34377044439315796, 0.1151578277349472, 0.15837147831916809, 0.074627704918384552, -0.31550765037536621, 0.093577876687049866, -0.38184052705764771, -0.058952804654836655, 0.10435575991868973, -0.41732195019721985, 
  -0.41281896829605103, -0.028326690196990967, 0.34306663274765015, 0.052679240703582764, -0.1234930157661438, 0.06988990306854248, 0.13174831867218018, 0.12597095966339111, 0.1842881441116333, 0.38683068752288818, -0.26947319507598877, 0.1752128005027771, 0.05614924430847168, 
  0.28497529029846191, -0.15615049004554749, -0.42957907915115356, -0.30867129564285278, 0.096664063632488251, -0.24964858591556549, 0.25263288617134094, 0.36713734269142151, 0.42212587594985962, -0.010592411272227764, -0.28985553979873657, 0.094558842480182648, -0.27983149886131287, 
  -0.34895297884941101, 0.22039443254470825, -0.22311195731163025, 0.24955129623413086, -0.034816086292266846, 0.24474555253982544, -0.041164994239807129, 0.40715265274047852, 0.20857745409011841, -0.3560035228729248, 0.34205466508865356, 0.33658504486083984, 0.20388847589492798, 
  0.32221049070358276, 0.13189853727817535, 0.087305136024951935, -0.29111766815185547, -0.36157941818237305, -0.33919182419776917, 0.32835766673088074, -0.12655553221702576, -0.22472083568572998, 0.22091342508792877, -0.15048955380916595, 0.050027772784233093, -0.29129022359848022, 
  -0.12592774629592896, 0.31603020429611206, 0.074660599231719971, -0.0182972252368927, -0.14248716831207275, -0.31831076741218567, 0.056696884334087372, 0.43608671426773071, -0.14788223803043365, 0.10772142559289932, -0.37741667032241821, -0.13630889356136322, -0.40026184916496277, 
  0.19016861915588379, -0.028823792934417725, -0.088763520121574402, -0.22505000233650208, -0.17087589204311371, -0.40675756335258484, -0.14971408247947693, 0.27601027488708496, -0.17645584046840668, 0.003991834819316864, -0.047929875552654266, -0.062301073223352432, -0.027127435430884361, 
  0.33518421649932861, -0.45057091116905212, 0.092927515506744385, 0.38487952947616577, 0.38917833566665649, 0.14338643848896027, 0.1384558379650116, 0.19546069204807281, -0.1099683940410614, 0.3790816068649292, -0.065131008625030518, 0.43128848075866699, -0.12417649477720261, 
  0.24204054474830627, 0.33886966109275818, 0.16271182894706726, -0.082687415182590485, -0.42359167337417603, 0.22796028852462769, -0.059082377701997757, -0.23695431649684906, -0.013599460944533348, -0.037983022630214691, 0.06076117604970932, 0.28847348690032959, 0.27494156360626221, 
  -0.35341614484786987, 0.18976640701293945, -0.35917356610298157, -0.027462154626846313, -0.24570614099502563, 0.27706471085548401, -0.35954225063323975, 0.0233649592846632, -0.20565706491470337, -0.39992871880531311, -0.33531752228736877, -0.26447850465774536, -0.39857649803161621, 
  0.39681547880172729, 0.1001429408788681, 0.15491779148578644, -0.43770140409469604, -0.40532991290092468, -0.19637197256088257, 0.2258363664150238, 0.053424905985593796, -0.039566442370414734, 0.12655061483383179, -0.33441945910453796, 0.11329289525747299, 0.099285617470741272, 
  -0.0579204261302948, 0.14286786317825317, 0.37580579519271851, -0.12817487120628357, -0.32388290762901306, -0.37736627459526062, 0.41977763175964355, -0.16626396775245667, 0.31017142534255981, -0.098268955945968628, 0.36223620176315308, 0.38844680786132812, 0.26924538612365723, 
  -0.1943180114030838, -0.40412119030952454, 0.0044142603874206543, -0.1357327401638031, 0.25638794898986816, -0.42574095726013184, -0.31316673755645752, -0.47180959582328796, -0.40275314450263977, 0.142032191157341, -0.15879936516284943, -0.45248040556907654, 0.043204959481954575, 
  0.083798408508300781, -0.31806653738021851, -0.15126755833625793, -0.0099983960390090942, 0.47832894325256348, 0.4391581118106842, -0.35195222496986389, 0.37832227349281311, -0.079931244254112244, 0.0725584477186203, 0.050916653126478195, 0.084325864911079407, 0.34542074799537659, 
  0.37704148888587952, -0.289539635181427, -0.17531658709049225, 0.092041365802288055, 0.11345454305410385, -0.23238919675350189, -0.18717491626739502, 0.13237036764621735, 0.18329936265945435, 0.1200830489397049, 0.3866182267665863, -0.43989479541778564, -0.38315293192863464, 
  0.013140869326889515, 0.24163191020488739, -0.39196166396141052, -0.40956726670265198, -0.49310067296028137, 0.082516133785247803, -0.058512225747108459, 0.083824895322322845, 0.17558179795742035, 0.1684710681438446, 0.0045816842466592789, 0.19142378866672516, -0.20715047419071198, 
  0.0056774318218231201, -0.27187860012054443, -0.16813677549362183, -0.030624061822891235, 0.34273773431777954, -0.13206540048122406, -0.17333559691905975, -0.3369733989238739, 0.12289033085107803, -0.40357911586761475, -0.40066945552825928, -0.16458971798419952, 0.067130342125892639, 
  -0.079813331365585327, 0.20870006084442139, 0.37691712379455566, 0.29858767986297607, 0.30768674612045288, -0.13088589906692505, -0.16504159569740295, 0.35310137271881104, 0.14580416679382324, -0.054791063070297241, -0.14958915114402771, 0.41184079647064209, -0.14955469965934753, 
  -0.35648927092552185, -0.10842558741569519, 0.22512394189834595, -0.41353702545166016, 0.20444262027740479, 0.054683756083250046, -0.25688815116882324, -0.021138684824109077, 0.0067981150932610035, -0.13014096021652222, -0.37264004349708557, -0.14332807064056396, -0.34321516752243042, 
  -0.026146678254008293, 0.34729915857315063, 0.069601818919181824, -0.22342865169048309, -0.068359464406967163, -0.1188647449016571, 0.1326628178358078, -0.058955982327461243, 0.29748743772506714, 0.28090992569923401, -0.34866893291473389, 0.33007752895355225, 0.2842138409614563, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,13 } };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,3 } };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,4 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,2,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,1,5 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, (int32_t*)(tensor_arena + 80), (TfLiteIntArray*)&g0::tensor_dimension0, 52, },
{ kTfLiteMmapRo, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 120, },
{ kTfLiteMmapRo, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 800, },
{ kTfLiteMmapRo, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, },
{ kTfLiteMmapRo, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 80, },
{ kTfLiteMmapRo, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 12, },
{ kTfLiteMmapRo, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 1040, },
{ kTfLiteArenaRw, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension7, 80, },
{ kTfLiteArenaRw, (int32_t*)(tensor_arena + 80), (TfLiteIntArray*)&g0::tensor_dimension8, 40, },
{ kTfLiteArenaRw, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 12, },
{ kTfLiteArenaRw, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 12, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = kTfLiteFloat32;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization.type = kTfLiteNoQuantization;

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = kTfLiteFloat32;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1125589_4_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1125589_4_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1125589_4_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1125589_4_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1125589_4_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
